language: objective-c
osx_image: xcode10.2
branches:
  only:
    - main
cache:
  directories:
    - $HOME/Library/Caches/org.carthage.CarthageKit/dependencies
    - Carthage
    - vendor/bundle

before_install:
  - bundle install --path vendor/bundle
  - gem install xcpretty
  - brew outdated carthage || brew upgrade carthage

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - WORKSPACE=BoxPreviewSDK.xcworkspace
    - IOS_FRAMEWORK_SCHEME="BoxPreviewSDK-iOS"
  matrix:
    - DESTINATION="OS=12.0,name=iPhone XS"                  SCHEME="$IOS_FRAMEWORK_SCHEME"     RUN_TESTS="YES"
    - DESTINATION="OS=11.4,name=iPhone X"                   SCHEME="$IOS_FRAMEWORK_SCHEME"     RUN_TESTS="YES"

before_script:
  - sh scripts/bootstrap

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Release and Run Tests if specified
  xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
#   - if [ $RUN_TESTS == "YES" ]; then
#       xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty -c;
#     else
#       xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
#     fi

jobs:
  include:
    # - stage: Danger
    #   script: bundle exec danger
    # - stage: Pod lib lint
    #   script: bundle exec pod lib lint --verbose --allow-warnings
    # - stage: Deploy Github
    #   script: skip
    #   before_deploy:
    #     - carthage build --no-skip-current --cache-builds
    #     - carthage archive BoxPreviewSDK
    #   deploy:
    #     - provider: releases
    #       api_key:
    #         secure: # https://docs.travis-ci.com/user/deployment/releases/
    #       file:
    #         - BoxPreviewSDK.framework.zip
    #       skip_cleanup: true
    #       overwrite: true
    #       on:
    #         repo: box/box-swift-preview-sdk
    #         tags: true
    # - stage: Deploy Cocoapods
    #   script: skip
    #   deploy:
    #     - provider: script # https://fuller.li/posts/automated-cocoapods-releases-with-ci/
    #       script: bundle exec pod trunk push
    #       skip_cleanup: true
    #       on:
    #         tags: true
