name: Manually triggered release
on:
  workflow_dispatch:
    inputs:
      preview_version:
        description: 'Please provide the version of box-ios-preview-sdk you want to release in format <MAJOR>.<MINOR>.<PATCH> e.g.: 1.0.0'
        required: true
      content_version:
        description: 'Please provide the latest released version of box-ios-sdk in format <MAJOR>.<MINOR>.<PATCH> e.g.: 1.0.0'
        required: true
jobs:
  release_box-ios-preview-sdk:
    runs-on: macos-11
    steps:
    - name: Authorize user
      env:
        AUTHORIZED_USERS: "${{ secrets.AUTHORIZED_USERS }}"
      run: |
         if [[ " ${AUTHORIZED_USERS} " =~ " ${{ github.actor }} " ]]; then echo "::notice::User is authorized to create release!"; else echo "::error::User is not authorized to create release"; exit 1; fi
    - name: Print parameters
      run: |
        echo "box-ios-preview-sdk <preview_version>: ${{ github.event.inputs.preview_version }}"
        echo "box-ios-sdk <content_version>: ${{ github.event.inputs.content_version }}"
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main
        token: ${{ secrets.GITHUB_TOKEN }}
        submodules: true
    - name: Setup git user
      run: |
          git config --global user.name "Artur Jankowski"
          git config --global user.email "ajankowski@box.com"
    - name: List Xcode available versions
      run: ls -n /Applications/ | grep Xcode*
    - name: Setup - Xcode
      run: sudo xcode-select -s /Applications/Xcode_12.5.1.app
    - name: Setup - Ruby and bundler dependencies
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Run fastlane release script
      run: |
        bundle exec fastlane ios release preview_version:${{ github.event.inputs.preview_version }} content_version:${{ github.event.inputs.content_version }} github_token:${{ secrets.RELEASE_TOKEN }}
