name: Pull request checklist
on: 
  pull_request:
    branches:
      - aj/test_workflow
jobs:
  Run-Tests:
    runs-on: macos-11
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=14.5,name=iPhone 11']
    steps:
      - name: Git - Checkout
        uses: actions/checkout@v2
      - name: List Xcode available versions
        run: ls -n /Applications/ | grep Xcode*
      - name: Setup - Xcode
        run: sudo xcode-select -s /Applications/Xcode_12.5.1.app
      - name: Setup - Ruby and bundler dependencies
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup carthage dependencies
        run: ./scripts/bootstrap
      - name: Lint
        run: swiftlint
      - name: Build project
        run: set -o pipefail && xcodebuild -workspace BoxPreviewSDK.xcworkspace -scheme BoxPreviewSDK-iOS  -destination "${{ matrix.destination }}" -configuration Release build
